name: DigitalStorage
author: Mooy1
description: A slimefun addon similar to the mod Refined Storage
main: io.github.mooy1.digitalstorage.DigitalStorage
website: https://github.com/Mooy1/DigitalStorage
version: ${project.version}
api-version: 1.16
depend: [Slimefun]